name: CI / Build & Deploy to Webflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Webflow Cloud
        if: ${{ secrets.WEBFLOW_CLOUD_TOKEN != '' }}
        env:
          WEBFLOW_CLOUD_TOKEN: ${{ secrets.WEBFLOW_CLOUD_TOKEN }}
        run: |
          echo "Running deploy script (will use WEBFLOW_CLOUD_TOKEN from secrets)"
          npm run deploy

      - name: Skip deploy if token missing
        if: ${{ secrets.WEBFLOW_CLOUD_TOKEN == '' }}
        run: echo "WEBFLOW_CLOUD_TOKEN not set — skipping deploy. Add the secret in repository settings to enable automatic deploys."
